### ISSUE TITLE
Campos de input com patterns não correspondentes 

### ISSUE THREAD

**Issue by AnneLivia** [pitanglabs/camunda-json-html-parser#3]
Ao fazer a conversão de JSON para HTML, todos os campos de textfield estão sendo retornados com um padrão regex: `^[a-zA-Z ]+$`, embora este padrão talvez não seja aplicado para todos os textfield.

**Comment by naftalima** [comment]
Cool!
Done https://github.com/pitanglabs/camunda-json-html-parser/pull/6 PR

**Comment by tenonin** [comment]
Done

**Comment by naftalima** [comment]
Fazer de caso a caso não é o ideal.
Issue https://github.com/pitanglabs/camunda-json-html-parser/issues/8
