### ISSUE TITLE
A implementação dos padrões na "força bruta" talvez não se encaixe em todos os casos

### ISSUE THREAD

**Issue by AnneLivia** [pitanglabs/camunda-json-html-parser#8]
A implementação dos padrões na "força bruta" talvez não se encaixe em todos os casos

_Originally posted by @AnneLivia in https://github.com/pitanglabs/camunda-json-html-parser/pull/7#issuecomment-2015249376_

**Comment by naftalima** [comment]
fechando a issue pra adicionar agrupar com a principal
